Repository tesla-local-control/tesla-local-control-addon, pull requests merged in 2024-07, with the labels that each got.

#62 Add warning on overheating / distance limits, especially on RPi
  tesla_ble_mqtt/README.md
Labels: bug

#96 Add missing installation counter
  README.md
Labels: documentation

#90 [feat] Auto MAC addr detection
  tesla_ble_mqtt/CHANGELOG.md
  tesla_ble_mqtt/DOCS.md
  tesla_ble_mqtt/config.yaml
  tesla_ble_mqtt/libproduct.sh
  tesla_ble_mqtt/translations/en.yaml
  tesla_ble_mqtt/translations/fr.yaml
Labels: enhancement
